version: '3.9'
services:
  auth-svc-dev:
    container_name: auth-svc-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    volumes:
      - .:/home/node/backend/auth-svc 
      - ./.docker/zsh/powerlevel10k/.p10k.zsh:/home/node/.p10k.zsh:delegated
      - ./.docker/zsh/history:/home/node/zsh:delegated
    depends_on:
      - micro-auth-dev
  micro-auth-dev:
    container_name: micro-auth-dev
    image: postgres:alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./.docker/postgres:/home/node/postgres/data
  auth-db-dev-test:
    container_name: auth-db-dev-test
    image: postgres:alpine3.18
    profiles:
      - test
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    tmpfs:
      - /var/lib/postgresql/data